### ISSUE TITLE
Update snippet to single escape character

### ISSUE THREAD

**Issue by maxwelldemonic** [digitalfiz/language-lsl#11]
The majority of snippets that have inserting lines and tabs use double escaped (\\) characters. This causes the editor to ignore the escape and simply print the character. Changing this to a single escape (\) will fix the issue.

**Comment by maxwelldemonic** [comment]
You could also just merge in the corrections made by Builders Brewery.

**Comment by digitalfiz** [comment]
I published a new version that should fix this. Let me know.

**Comment by maxwelldemonic** [comment]
Seems to be kicking back a much bigger problem after that patch.

Uncaught Error: premature end of char-class

[Stack Trace Gist](https://gist.github.com/maxwelldemonic/200afa5fd0413d3622c8#file-gistfile1-txt)

This happens upon loading an LSL file or any file Atom has set to highlight as LSL

**Comment by digitalfiz** [comment]
I will look at it this evening and do some full testing.

**Comment by maxwelldemonic** [comment]
Much appreciated, Lemme know if there is anything I can help with.

**Comment by valpet** [comment]
I too would love to have this issue solved. Any update?

**Comment by DakotaWolfi** [comment]
i think i try to upload the old version on my page :) then my version is working
i had the same problem with the new version
this is version 2.0.3 it should work
[language-lsl.zip](https://github.com/digitalfiz/language-lsl/files/209727/language-lsl.zip)

**Comment by maxwelldemonic** [comment]
Builders Brewery has a version that almost works (It's fine once you change their version number to be 1.0.0 instead of 1.0).
